name: alejandria
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipywidgets
  - jupyterlab
  - pandas
  - pip:
    - autogen-agentchat~=0.2
    - dask[dataframe]
    - dash
    - groq
    - flaml[automl]
    - graphviz
    - google-search-results
    - hdbscan
    - ipympl
    - jupyter-book
    - matplotlib
    - mpl-tools
    - ollama
    - openai
    - pillow
    - plotly
    - pyautogen[ollama]
    - PyMuPDF
    - pydot
    - python-docx
    - python-dotenv
    - scikit-learn
    - scipy
    - seaborn
    - sentence-transformers
    - sqlalchemy
    - statsmodels
    - streamlit
    - tqdm
    - umap-learn
    - umap-learn[plot]